#!/usr/bin/env python3
"""Build GIMPhoto's default shortcuts from its Photoshop keymap.

    tools/make_keymap.py [work/gimp]            write defaults/shortcutsrc
    tools/make_keymap.py --check [work/gimp]    exit 1 if it is out of date
    tools/make_keymap.py --markdown [work/gimp] print the docs table only

Input:  defaults/photoshop-keymap.tsv, GIMPhoto's own table of Photoshop's
        default shortcuts on GIMP actions; defaults/shortcut-moves.tsv, the
        shortcuts GIMPhoto has moved since (for profiles that already have
        their own shortcutsrc); and GIMP's own default shortcuts, read from
        its source (tools/gimp_default_accels.py).
Output: defaults/shortcutsrc, in GIMP's shortcutsrc format, and the keymap
        table in docs/features/photoshop-shortcuts.md. GIMPhoto's patch
        to app/menus/menus.c loads it when the profile has no shortcutsrc of
        its own (a new profile, or after "Reset Keyboard Shortcuts").

Every action in the table gets its Photoshop shortcuts plus the GIMP ones
nothing else takes; every other action whose GIMP shortcut the table takes
loses that shortcut (and keeps its others), so no key does two things.
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gimp_default_accels import default_accels

ROOT = Path(__file__).resolve().parent.parent
PLUGINS = ROOT / "plugins"
# GIMPhoto's plug-in procedures, which are GIMP actions of the same name:
# NAME_PROC = "gimphoto-..." in plugins/<name>/<name>.py
PROC = re.compile(r'^[A-Z_]*PROC\s*=\s*"(gimphoto-[a-z0-9-]+)"', re.M)
KEYMAP = ROOT / "defaults" / "photoshop-keymap.tsv"
MOVES = ROOT / "defaults" / "shortcut-moves.tsv"
OUTPUT = ROOT / "defaults" / "shortcutsrc"
DOC = ROOT / "docs" / "features" / "photoshop-shortcuts.md"
DOC_START = "<!-- keymap:start (generated by tools/make_keymap.py, do not edit) -->\n"
DOC_END = "<!-- keymap:end -->"
MODIFIERS = {
    "primary": "<Primary>",
    "control": "<Primary>",
    "ctrl": "<Primary>",
    "shift": "<Shift>",
    "alt": "<Alt>",
    "mod1": "<Alt>",
    "super": "<Super>",
}
# Action groups GIMP creates after reading shortcutsrc (when the tool first
# runs), so lines for them are ignored. They keep GIMP's shortcuts; the text
# tool handles its Ctrl+B/I/U and Ctrl+Shift+V itself while editing, before
# any shortcut, so they do not clash with the keymap's.
LATE_ACTIONS = ("text-tool-",)
ACCEL = re.compile(r"^((?:<[A-Za-z0-9]+>)*)([^<>\s]+)$")
HEADER = """\
# GIMPhoto's default shortcuts: Photoshop's, from defaults/photoshop-keymap.tsv.
# GENERATED by tools/make_keymap.py. Do not edit by hand.
#
# GIMPhoto loads this file when your profile has no shortcutsrc of its own;
# your changes are saved there. The table is GIMPhoto's own; PhotoGIMP
# (github.com/Diolinux/PhotoGIMP) was a reference for which GIMP action
# matches which Photoshop command.

(file-version 1)

"""


def normalize(accel):
    """A comparable form of a GTK accelerator: "<Control>D" and "<primary>d"
    are the same key. Raises ValueError for anything that is not one."""
    m = ACCEL.match(accel.strip())
    if not m:
        raise ValueError(f"not a shortcut: {accel!r}")
    mods = set()
    for mod in re.findall(r"<([A-Za-z0-9]+)>", m.group(1)):
        if mod.lower() not in MODIFIERS:
            raise ValueError(f"unknown modifier <{mod}> in {accel!r}")
        mods.add(MODIFIERS[mod.lower()])
    order = ["<Primary>", "<Alt>", "<Shift>", "<Super>"]
    return "".join(mod for mod in order if mod in mods) + m.group(2).lower()


def plugin_actions():
    """GIMPhoto's own plug-in procedures, as actions without shortcuts."""
    names = []
    for path in sorted(PLUGINS.glob("*/*.py")):
        names += PROC.findall(path.read_text())
    return {name: [] for name in names}


def read_keymap(text):
    """[(action, [accels], Photoshop command)] from the keymap table."""
    rows = []
    for number, line in enumerate(text.splitlines(), 1):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        fields = line.split("\t")
        if len(fields) != 3 or not all(f.strip() for f in fields):
            raise ValueError(f"line {number}: want action<TAB>shortcuts<TAB>command, got {line!r}")
        action, accels, command = (f.strip() for f in fields)
        rows.append((action, [a.strip() for a in accels.split(",")], command))
    return rows


def read_moves(text, shortcuts):
    """[(version, accel, old action, new action)] from the moves table,
    checked against the shortcuts being written: the new action has the
    shortcut, the old one no longer does."""
    moves = []
    for number, line in enumerate(text.splitlines(), 1):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        fields = [f.strip() for f in line.split("\t")]
        if len(fields) != 4 or not fields[0].isdigit() or int(fields[0]) < 1:
            raise ValueError(f"line {number}: want version<TAB>shortcut<TAB>old action<TAB>new action, got {line!r}")
        version, accel, old, new = int(fields[0]), *fields[1:]
        key = normalize(accel)
        if key not in {normalize(a) for a in shortcuts.get(new, [])}:
            raise ValueError(f"line {number}: {new} does not have {accel} in the keymap")
        if key in {normalize(a) for a in shortcuts.get(old, [])}:
            raise ValueError(f"line {number}: {old} still has {accel}")
        moves.append((version, accel, old, new))
    return moves


def build(keymap, defaults):
    """{action: [accels]} to write: the keymap's actions, and the other
    actions whose GIMP shortcuts the keymap takes."""
    taken = {}
    for action, accels, _ in keymap:
        if action not in defaults:
            raise ValueError(f"GIMP has no action {action!r}")
        for accel in accels:
            key = normalize(accel)
            if key in taken:
                raise ValueError(f"{accel} is on both {taken[key]} and {action}")
            taken[key] = action
    mapped = [action for action, _, _ in keymap]
    if len(set(mapped)) != len(mapped):
        raise ValueError("an action is in the keymap twice")

    result = {}
    for action, accels, _ in keymap:
        result[action] = list(accels) + [a for a in defaults[action] if normalize(a) not in taken]
    for action, accels in defaults.items():
        if action.startswith(LATE_ACTIONS):
            continue
        if action not in result and any(normalize(a) in taken for a in accels):
            result[action] = [a for a in accels if normalize(a) not in taken]
    return result


def render(shortcuts, moves=()):
    lines = [HEADER]
    if moves:
        lines.append("# Moved shortcuts, applied once to profiles that have their own shortcutsrc:\n")
        lines += [f'# gimphoto-shortcut-moved {v} "{accel}" "{old}" "{new}"\n' for v, accel, old, new in moves]
        lines.append("\n")
    for action in sorted(shortcuts):
        accels = "".join(f' "{a}"' for a in shortcuts[action])
        lines.append(f'(action "{action}"{accels})\n')
    return "".join(lines)


KEY_NAMES = {
    "bracketleft": "[",
    "bracketright": "]",
    "semicolon": ";",
    "apostrophe": "'",
    "comma": ",",
    "period": ".",
    "grave": "`",
    "plus": "+",
    "equal": "=",
    "minus": "-",
    "backspace": "Backspace",
    "kp_add": "Keypad +",
    "kp_subtract": "Keypad -",
    "kp_1": "Keypad 1",
}


def human(accel):
    """How a person writes a shortcut: "<Primary><Shift>bracketright" is
    Ctrl+Shift+]."""
    key = normalize(accel)
    mods = re.findall(r"<([A-Za-z]+)>", key)
    name = accel[accel.rfind(">") + 1 :]
    name = KEY_NAMES.get(name.lower(), name.upper() if len(name) == 1 else name[:1].upper() + name[1:])
    words = {"Primary": "Ctrl"}
    return "+".join([*(words.get(m, m) for m in mods), name])


def markdown(keymap, defaults):
    """The docs table: Photoshop command, shortcut, GIMP's old shortcut."""
    rows = ["| Photoshop command | GIMPhoto | GIMP action | Plain GIMP |", "|---|---|---|---|"]
    for action, accels, command in keymap:
        new = ", ".join(human(a) for a in accels)
        old = ", ".join(human(a) for a in defaults[action]) or "–"
        rows.append(f"| {command} | {new} | `{action}` | {old} |".replace("|`|", "|"))
    return "\n".join(rows) + "\n"


def with_table(doc, table):
    """The docs page with the table between its keymap markers replaced."""
    start = doc.index(DOC_START) + len(DOC_START)
    return doc[:start] + table + doc[doc.index(DOC_END, start) :]


def main(argv):
    flags = {a for a in argv[1:] if a.startswith("--")}
    args = [a for a in argv[1:] if not a.startswith("--")]
    source = Path(args[0] if args else ROOT / "work" / "gimp")
    if not (source / "app" / "actions").is_dir():
        sys.exit(f"{source} is not a GIMP source tree (run scripts/source)")
    defaults = {**default_accels(source), **plugin_actions()}
    try:
        keymap = read_keymap(KEYMAP.read_text())
        shortcuts = build(keymap, defaults)
    except ValueError as error:
        sys.exit(f"{KEYMAP.relative_to(ROOT)}: {error}")
    try:
        moves = read_moves(MOVES.read_text(), shortcuts)
    except ValueError as error:
        sys.exit(f"{MOVES.relative_to(ROOT)}: {error}")
    text = render(shortcuts, moves)
    table = markdown(keymap, defaults)
    if "--markdown" in flags:
        sys.stdout.write(table)
        return 0
    doc = DOC.read_text()
    outputs = {OUTPUT: text, DOC: with_table(doc, table)}
    if "--check" in flags:
        stale = [path for path, want in outputs.items() if not path.exists() or path.read_text() != want]
        for path in stale:
            print(f"{path.relative_to(ROOT)} is out of date: run tools/make_keymap.py", file=sys.stderr)
        return 1 if stale else 0
    for path, want in outputs.items():
        path.write_text(want)
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
