#!/usr/bin/env python3
"""Generate GIMPhoto's Flatpak manifest from Flathub's GIMP manifest.

    tools/make_manifest.py            write flatpak/<APP_ID>.json
    tools/make_manifest.py --check    exit 1 if that file is out of date

Input:  flatpak/upstream/org.gimp.GIMP.json, vendored from
        https://github.com/flathub/org.gimp.GIMP (commit in
        flatpak/upstream/FLATHUB_COMMIT; refreshed by scripts/sync-flathub).
        patches/series, GIMPhoto's own changes to GIMP's source, in order.
Output: flatpak/io.github.diegochagas.GIMPhoto.json, committed so every
        build (local, CI, contributors) uses exactly the same recipe.

What changes against Flathub's recipe, and nothing else:
  - the app ID and the launcher name, so GIMPhoto installs next to the
    official GIMP instead of replacing it;
  - Flathub's own GIMP patch is read from flatpak/upstream/patches/;
  - GIMPhoto's patches are applied to GIMP's source after Flathub's.
The GIMP version, every library, the build options and the sandbox
permissions stay Flathub's.
"""

import copy
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UPSTREAM = ROOT / "flatpak" / "upstream" / "org.gimp.GIMP.json"
SERIES = ROOT / "patches" / "series"
APP_ID = "io.github.diegochagas.GIMPhoto"
APP_NAME = "GIMPhoto"
OUTPUT = ROOT / "flatpak" / f"{APP_ID}.json"


def read_series():
    """Patch file names from patches/series: one per line, # comments."""
    if not SERIES.exists():
        return []
    names = []
    for line in SERIES.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            if not (ROOT / "patches" / line).is_file():
                sys.exit(f"patches/series lists {line}, which is not in patches/")
            names.append(line)
    return names


def transform(manifest, series):
    m = copy.deepcopy(manifest)
    m["app-id"] = APP_ID
    # Flathub renames the desktop file, icon and AppStream file to the app
    # ID; flatpak-builder does the same with ours.
    gimp = next((mod for mod in m["modules"] if isinstance(mod, dict) and mod.get("name") == "gimp"), None)
    if gimp is None:
        sys.exit("Flathub's manifest has no 'gimp' module: the generator needs updating")
    for source in gimp["sources"]:
        if isinstance(source, dict) and source.get("type") == "patch":
            source["paths"] = [f"upstream/{p}" for p in source["paths"]]
    if series:
        gimp["sources"].append(
            {"type": "patch", "use-git-am": True, "paths": [f"../patches/{name}" for name in series]}
        )
    # The launcher says GIMPhoto, so it can be told apart from GIMP.
    gimp.setdefault("post-install", []).append(
        "desktop-file-edit --set-name=" + APP_NAME + " ${FLATPAK_DEST}/share/applications/gimp.desktop"
    )
    return m


def render():
    manifest = json.loads(UPSTREAM.read_text())
    header = {
        "//": "GENERATED by tools/make_manifest.py from flatpak/upstream/org.gimp.GIMP.json "
        "and patches/series. Do not edit by hand."
    }
    return json.dumps({**header, **transform(manifest, read_series())}, indent=4) + "\n"


def main():
    text = render()
    if "--check" in sys.argv[1:]:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date: run tools/make_manifest.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
